### ISSUE TITLE
Feature request: Request MTU size

### ISSUE THREAD

**Issue by RyanYANG52** [pauldemarco/flutter_blue#129]
First of all, thanks for this awesome project.

I'm write an app using BLE to listen to some sensor data, I was able to receive notify value on a characteristic. But mtu size is 23 bytes by default, so I can only read the first 20 bytes, I didn't find any api to request a large size. My sensor data length is mutable and could be large than 23.

My app is running on > Android API 21. Here I found a [stackoverflow post](https://stackoverflow.com/questions/30904341/requesting-mtu-with-bluetooth-low-energy-connection-on-android-4-3-4-4-api-18-2)

**Comment by bondjpf** [comment]
MTU size is very important. I hope devs can add this feature so more people can start using this.

**Comment by wabash9000** [comment]
+1 For this.  On iOS I don't have to do this and can very quickly send 136 byte packets.  On Android I am unable to send anything greater than 23 bytes and the transfer takes quite a bit longer because of the overhead built into BLE.

I found that I can receive 136 byte packets from the bluetooth device, but I am unable to send them.  If I send an 8 byte packet on the characteristic, the device will reply with a 136 byte packet.

**Comment by RyanYANG52** [comment]
you can create a pull request @wabash9000

**Comment by LastMonopoly** [comment]
If you want to send more than 23 bytes on android, use writeWithResponse instead of writeWithoutResponse

**Comment by pauldemarco** [comment]
@RyanYANG52  @bondjpf @LastMonopoly 
I have implemented MTU functionality in the latest version of the plugin (0.6.1).
Please try it out and let me know your feedback.
