### ISSUE TITLE
Protobuf Gradle plugin version 0.8.6 and higher vs Project 'flutter_blue' is using version 0.8.3

### ISSUE THREAD

**Issue by icarus31** [pauldemarco/flutter_blue#141]
Using:
- VS Code: 1.29.1
- Flutter: 1.0.0
- Flutter_blue: 0.4.1

When starting the debugger, I got:

```
* Error running Gradle:
ProcessException: Process "C:\Development\flutter\bluetooth_example\android\gradlew.bat" exited abnormally:
> Configure project :flutter_blue
The com.google.protobuf plugin was already applied to the project: :flutter_blue and will not be applied again after plugin: android-library

FAILURE: Build failed with an exception.
* What went wrong:
The Android Gradle plugin supports only Protobuf Gradle plugin version 0.8.6 and higher. Project 'flutter_blue' is using version 0.8.3.
```

**Comment by pauldemarco** [comment]
Fixed in 2cf8cecb2f0f2bd80dd8562fa9ed8de0102954ef

**Comment by darnoldtux** [comment]
I am having the same problem as @ai-curry. I have not been able to find a work around.

**Comment by pauldemarco** [comment]
This is fixed on master branch. I will publish a patch on publang today.

Thanks for your patience.

On Dec 28, 2018 11:19 AM, "darnoldtux" <notifications@github.com> wrote:

I am having the same problem as @ai-curry <https://github.com/ai-curry>. I
have not been able to find a work around.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/pauldemarco/flutter_blue/issues/141#issuecomment-450385215>,
or mute the thread
