### ISSUE TITLE
Connect to a BLE Device Without Searching

### ISSUE THREAD

**Issue by IAmSarthakVerma** [pauldemarco/flutter_blue#490]
Can we connect to a BLE Device without scanning if we know the name of the BLE firsthand?

**Comment by Fleximex** [comment]
You can using the MAC-Address.

**Comment by IAmSarthakVerma** [comment]
@Fleximex Can you please show a small sample code or just one line of how to modify device.connect().

**Comment by Fleximex** [comment]
You should create the Device object yourself. Use that to connect (``device.connect()``).
The only problem is that there is no constructor since a commit made in December 2018. You can change the code to add a constructor yourself or figure out how to use the from Proto method.
https://github.com/pauldemarco/flutter_blue/issues/344

**Comment by boskokg** [comment]
Also take a note that you can connect using MAC address only on Android (on iOS you cannot).

**Comment by pauldemarco** [comment]
Constructing BluetoothDevices manually is not recommended as it won’t work cross platform (only works on Android since iOS doesn’t allow connection by MAC address)

The recommended approach is to scan for devices nearby, filter out the one you are looking for, then connect to it.
